# -*- coding: utf-8 -*-
"""Hora+da+pratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ooh6ElcbG8PI9rWwGaxm_jhWLsEI4MSZ

# Sobre o notebook

A "hora da prática" é uma atividade do curso de Python para Data Science da Alura que contém diversos desafios envolvendo os aprendizados de cada aula.

O notebook "hora da pratica" é um notebook construído com espaço para as células dos desafios propostos no curso, com ele você tem espaço para construir e executar suas soluções

## Aula 1 - Introdução ao Python

### Questão 1

Imprima a frase `Escola de Dados da Alura!`
"""

print('Escola de Dados Alura!')

"""### Questão 2
Imprima na tela seu nome e seu sobrenome seguindo a estrutura abaixo:
```
Nome: [seu nome]
Sobrenome: [seu sobrenome]
```

"""

nome = 'Fernanda'
sobrenome = 'Alexandre Mancini'

print(f'Nome: {nome}')
print(f'Sobrenome: {sobrenome}')

"""### Questão 3
Imprima o seu primeiro nome letra a letra. Por exemplo, nome é Mirla, então eu obtenho a seguinte saída:
```
M
I
R
L
A
```

"""

print(nome[0])
print(nome[1])
print(nome[2])
print(nome[3])
print(nome[4])
print(nome[5])
print(nome[6])
print(nome[7])

"""### Questão 4
Imprima o dia do seu nascimento em formato `dia mês ano`. Os valores de dia e ano não podem estar entre aspas. O formato deve estar como no exemplo, supondo uma data de aniversário dia 28 de fevereiro de 2003:
```
28 fevereiro 2003
```
"""

dia = 7
mes = 'julho'
ano = 2004

print(f'{dia} {mes} {ano}')

"""### Questão 5
Imprima em um único print o atual ano que você está fazendo esse curso, o valor do ano deve ser um dado numérico. A saída do print deve ser a seguinte:
```
Ano atual: [ano]
```

"""

ano_atual = 2025
print(f'Ano atual: {2025}')

"""## Aula 2 - Manipulando dados no Python

### Coleta e amostragem de dados

#### Questão 1
Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
"""

nome = input('Qual o seu nome: ')
print(f'Olá, {nome}')

"""#### Questão 2
Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.
"""

nome = input('Qual o seu nome: ')
idade = int(input('Quantos anos você tem: '))
print(f'Olá, {nome}, você tem {idade} anos')

"""#### Questão 3
Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.
"""

nome = input('Qual o seu nome: ')
idade = int(input('Quantos anos você tem: '))
metros = float(input('Qual a sua altura: '))
print(f'Olá, {nome}, você tem {idade} anos e mede {metros} metros!')

"""### Calculadora com operadores

#### Questão 1

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
"""

num1 = int(input('Escolha um número: '))
num2 = int(input('Escolha outro número: '))
print(f'A soma dos números digitados é: {num1 + num2}')

"""#### Questão 2
Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
"""

num1 = int(input('Escolha um número: '))
num2 = int(input('Escolha outro número: '))
num3 = int(input('Escolha mais um número: '))
print(f'A soma dos números digitados é: {num1 + num2 + num3}')

"""#### Questão 3
Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
"""

num1 = int(input('Escolha um número: '))
num2 = int(input('Escolha outro número: '))
print(f'A diferença dos números digitados é: {num1 - num2}')

"""#### Questão 4

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

"""

num1 = int(input('Escolha um número: '))
num2 = int(input('Escolha outro número: '))
print(f'A multiplicação dos números digitados é: {num1 * num2}')

"""#### Questão 5

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.

"""

num1 = int(input('Escolha o numerador: '))
num2 = int(input('Escolha o denominador: '))
print(f'A divisão de {num1} por {num2} é: {num1 / num2}')

"""#### Questão 6

Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

"""

num1 = int(input('Escolha o número base: '))
num2 = int(input('Escolha outro número para a potência: '))
print(f'{num1} elevado a {num2} é: {num1 ** num2}')

"""#### Questão 7
Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

num1 = int(input('Escolha um numerador: '))
while True:
   num2 = int(input('Escolha o denominador: '))
   if num2 !=0:
      break
   else:
      print('O denominador não pode ser zero!')

print(f'A divisão de {num1} por {num2} é: {num1 / num2}')

"""#### Questão 8

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

num1 = int(input('Escolha um numerador: '))
while True:
   num2 = int(input('Escolha o denominador: '))
   if num2 !=0:
      break
   else:
      print('O denominador não pode ser zero!')

print(f'O resto da divisão de {num1} por {num2} é: {num1 % num2}')

"""#### Questão 9

Crie um código que solicita 3 notas de um estudante e imprima a média das notas.
"""

num1 = float(input('Digite a Primeira Nota: '))
num2 = float(input('Digite a Segunda Nota: '))
num3 = float(input('Digite a Terceira Nota: '))
print(f'A média das notas é: {(num1 + num2 + num3)/3:.2f}')

"""#### Questão 10

Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.
"""

print(f'A média ponderada de 5, 12, 20 e 15 é: {(5*1 + 12*2 + 20*3 + 15*4)/(1 + 2 + 3 + 4)}')

"""### Editando textos

#### Questão 1

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
"""

frase = 'Isso é uma frase'
print(frase)

"""#### Questão 2
Crie um código que solicite uma frase e depois imprima a frase na tela.
"""

frase = input('Escreva uma frase: ')
print(frase)

"""#### Questão 3

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
"""

frase = input('Escreva uma frase: ')
print(frase.upper())

"""#### Questão 4

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
"""

frase = input('Escreva uma frase: ')
print(frase.lower())

"""#### Questão 5

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
"""

frase = '      Batata é bom          '
print(frase.strip())

"""#### Questão 6

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
"""

frase = input('Escreva uma frase: ')
print(frase.strip())

"""#### Questão 7


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
"""

frase = input('Escreva uma frase: ')
print(frase.strip().lower())

"""#### Questão 8

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`e`” trocadas pela letra “`f`”.
"""

frase = input('Escreva uma frase: ')
print(frase.replace('e', 'f'))

"""#### Questão 9


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`a`” trocadas pela caractere  “`@`”.
"""

frase = input('Escreva uma frase: ')
print(frase.replace('a', '@'))

"""#### Questão 10


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “`s`” trocadas pelo caractere  “`$`”.
"""

frase = input('Escreva uma frase: ')
print(frase.replace('s', '$'))

"""## Aula 3 - Estruturas condicionais

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior.
"""

num1 = int(input('Digite um número: '))
num2 = int(input('Digite outro número: '))
if num1 > num2:
  print(f'{num1} é maior que {num2}')
elif num1 < num2:
  print(f'{num2} é maior que {num1}')
else:
  print(f'Os números {num1} e {num2} são iguais')

"""#### Questão 2
Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).
"""

percentual = float(input('Digite o percentual de crescimento da produção (%): '))

if percentual > 0:
    print('Houve crescimento na produção.')
elif percentual < 0:
    print('Houve decrescimento na produção.')
else:
    print('A produção se manteve estável.')

"""#### Questão 3
Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante.
"""

letra = input('Digite uma letra: ').lower()
if letra in 'aeiou':
    print('É vogal')
else:
    print('É consoante')

"""#### Questão 4
Escreva um programa que leia valores médios de preços de um modelo de carro por 3 anos consecutivos e exiba o valor mais alto e mais baixo entre esses três anos.
"""

preco1 = int(input('Qual é o valor do carro no ano um: '))
preco2 = int(input('Qual é o valor do carro no ano dois: '))
preco3 = int(input('Qual é o valor do carro no ano três: '))
carro = [preco1, preco3, preco3]
carro.sort()
print(f'O valor mais alto do carro foi: {carro[2]}')
print(f'O valor mais baixo do carro foi: {carro[0]}')

"""#### Questão 5
Escreva um programa que pergunte sobre o preço de três produtos e indique qual é o produto mais barato para comprar.
"""

preco1 = float(input("Digite o preço do primeiro produto: R$ "))
preco2 = float(input("Digite o preço do segundo produto: R$ "))
preco3 = float(input("Digite o preço do terceiro produto: R$ "))

if preco1 < preco2 and preco1 < preco3:
    print("Você deve comprar o primeiro produto.")
elif preco2 < preco1 and preco2 < preco3:
    print("Você deve comprar o segundo produto.")
elif preco3 < preco1 and preco3 < preco2:
    print("Você deve comprar o terceiro produto.")
else:
    print("Há dois ou mais produtos com o mesmo menor preço.")

"""#### Questão 6
Escreva um programa que leia três números e os exiba em ordem decrescente.
"""

num1 = int(input('Digite um número: '))
num2 = int(input('Digite outro número: '))
num3 = int(input('Digite outro número: '))
lista = [num1, num2, num3]
lista.sort()
print(f'Números em ordem decrescente: {lista[2]}, {lista[1]}, {lista[0]}')

"""#### Questão 7
Escreva um programa que pergunte em qual turno a pessoa usuária estuda ("manhã", "tarde" ou "noite") e exiba a mensagem "Bom Dia!", "Boa Tarde!", "Boa Noite!", ou "Valor Inválido!", conforme o caso.
"""

turno = input("Em qual turno você estuda? (manhã, tarde ou noite): ").strip().lower()

if turno == "manhã":
    print("Bom Dia!")
elif turno == "tarde":
    print("Boa Tarde!")
elif turno == "noite":
    print("Boa Noite!")
else:
    print("Valor Inválido!")

"""#### Questão 8
Escreva um programa que peça um número inteiro à pessoa usuária e determine se ele é par ou ímpar. Dica: Você pode utilizar o operador módulo `%`.
"""

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
    print("O número é par.")
else:
    print("O número é ímpar.")

"""#### Questão 9
Escreva um programa que peça um número à pessoa usuária e informe se ele é inteiro ou decimal.
"""

numero_str = input("Digite um número: ")

try:
    numero = float(numero_str)
    if numero.is_integer():
        print("O número é inteiro.")
    else:
        print("O número é decimal.")
except ValueError:
    print("Valor inválido! Por favor, digite um número válido.")

"""### Momento dos projetos

#### Questão 10
Um programa deve ser escrito para ler dois números e, em seguida, perguntar à pessoa usuária qual operação ele deseja realizar. O resultado da operação deve incluir informações sobre o número - se é par ou ímpar, positivo ou negativo e inteiro ou decimal.
"""

def analisar_numero(resultado):
    if resultado % 2 == 0:
        par_ou_impar = "par"
    else:
        par_ou_impar = "ímpar"

    if resultado > 0:
        sinal = "positivo"
    elif resultado < 0:
        sinal = "negativo"
    else:
        sinal = "zero"

    if resultado == int(resultado):
        tipo = "inteiro"
    else:
        tipo = "decimal"

    return f"O resultado é {resultado}.\nEle é {par_ou_impar}, {sinal} e {tipo}."

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

print("Escolha a operação desejada:")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

operacao = input("Digite o número da operação (1 a 4): ")

if operacao == "1":
    resultado = num1 + num2
elif operacao == "2":
    resultado = num1 - num2
elif operacao == "3":
    resultado = num1 * num2
elif operacao == "4":
    if num2 != 0:
        resultado = num1 / num2
    else:
        print("Erro: divisão por zero!")
        exit()
else:
    print("Operação inválida.")
    exit()

print(analisar_numero(resultado))

"""#### Questão 11
Escreva um programa que peça à pessoa usuária três números que representam os lados de um triângulo. O programa deve informar se os valores podem ser utilizados para formar um triângulo e, caso afirmativo, se ele é equilátero, isósceles ou escaleno. Tenha em mente algumas dicas:
- Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
- Triângulo Equilátero: três lados iguais;
- Triângulo Isósceles: quaisquer dois lados iguais;
- Triângulo Escaleno: três lados diferentes;

"""

lado1 = float(input("Digite o primeiro lado do triângulo: "))
lado2 = float(input("Digite o segundo lado do triângulo: "))
lado3 = float(input("Digite o terceiro lado do triângulo: "))

if (lado1 + lado2 > lado3) and (lado1 + lado3 > lado2) and (lado2 + lado3 > lado1):
    print("Os lados formam um triângulo.")

    if lado1 == lado2 == lado3:
        print("Tipo: Triângulo Equilátero.")
    elif lado1 == lado2 or lado1 == lado3 or lado2 == lado3:
        print("Tipo: Triângulo Isósceles.")
    else:
        print("Tipo: Triângulo Escaleno.")
else:
    print("Os lados NÃO formam um triângulo.")

"""#### Questão 12
Um estabelecimento está vendendo combustíveis com descontos variados. Para o etanol, se a quantidade comprada for até 15 litros, o desconto será de 2% por litro. Caso contrário, será de 4% por litro. Para o diesel, se a quantidade comprada for até 15 litros, o desconto será de 3% por litro. Caso contrário, será de 5% por litro. O preço do litro de diesel é R\$ 2,00 e o preço do litro de etanol é R\$ 1,70. Escreva um programa que leia a quantidade de litros vendidos e o tipo de combustível (E para etanol e D para diesel) e calcule o valor a ser pago pelo cliente. Tenha em mente algumas dicas:

- O do valor do desconto será a multiplicação entre preço do litro, quantidade de litros e o valor do desconto.
- O valor a ser pago por um cliente será o resultado da multiplicação do preço do litro pela quantidade de litros menos o valor de desconto resultante do cálculo.

"""

preco_etanol = 1.70
preco_diesel = 2.00

litros = float(input("Digite a quantidade de litros vendidos: "))
tipo = input("Digite o tipo de combustível (E para etanol, D para diesel): ").strip().upper()

preco_litro = 0
desconto_porcentagem = 0

if tipo == "E":
    preco_litro = preco_etanol
    if litros <= 15:
        desconto_porcentagem = 0.02
    else:
        desconto_porcentagem = 0.04
elif tipo == "D":
    preco_litro = preco_diesel
    if litros <= 15:
        desconto_porcentagem = 0.03
    else:
        desconto_porcentagem = 0.05
else:
    print("Tipo de combustível inválido.")
    exit()

valor_bruto = preco_litro * litros
valor_desconto = valor_bruto * desconto_porcentagem
valor_final = valor_bruto - valor_desconto

print(f"\nTipo de combustível: {'Etanol' if tipo == 'E' else 'Diesel'}")
print(f"Valor bruto: R$ {valor_bruto:.2f}")
print(f"Desconto aplicado: R$ {valor_desconto:.2f}")
print(f"Valor final a pagar: R$ {valor_final:.2f}")

"""#### Questão 13
Em uma empresa de venda de imóveis você precisa criar um código que analise os dados de vendas anuais para ajudar a diretoria na tomada de decisão. O código precisa coletar os dados de quantidade de venda durante os anos de 2022 e 2023 e fazer um cálculo de variação percentual. A partir do valor da variação, deve ser enviada às seguintes sugestões:
- Para variação acima de 20%: bonificação para o time de vendas.
- Para variação entre 2% e 20%: pequena bonificação para time de vendas.
- Para variação entre 2% e -10%: planejamento de políticas de incentivo às vendas.
- Para bonificações abaixo de -10%: corte de gastos.

"""

vendas_2022 = int(input("Digite a quantidade de vendas em 2022: "))
vendas_2023 = int(input("Digite a quantidade de vendas em 2023: "))

if vendas_2022 == 0:
    print("Não é possível calcular a variação percentual com zero vendas em 2022.")
else:
    variacao = ((vendas_2023 - vendas_2022) / vendas_2022) * 100
    print(f"\nVariação percentual: {variacao:.2f}%")

    if variacao > 20:
        print("Recomendação: Bonificação para o time de vendas.")
    elif 2 < variacao <= 20:
        print("Recomendação: Pequena bonificação para o time de vendas.")
    elif -10 <= variacao <= 2:
        print("Recomendação: Planejamento de políticas de incentivo às vendas.")
    elif variacao < -10:
        print("Recomendação: Corte de gastos.")

"""## Aula 4 - Estruturas de repetição

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça dois números inteiros e imprima todos os números inteiros entre eles.
"""

num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))

inicio = min(num1, num2) + 1
fim = max(num1, num2)

if inicio >= fim:
    print("Não há números inteiros entre os dois valores informados.")
else:
    print("Números inteiros entre os dois valores:")
    for i in range(inicio, fim):
        print(i)

"""#### Questão 2
Escreva um programa para calcular quantos dias levará para a colônia de uma bactéria A ultrapassar ou igualar a colônia de uma bactéria B, com base nas taxas de crescimento de 3% e 1,5% respectivamente. Considere que a colônia A inicia com 4 elementos e a colônia B com 10 elementos.
"""

colonia_A = 4
colonia_B = 10
dias = 0

while colonia_A < colonia_B:
    colonia_A *= 1.03  # crescimento de 3%
    colonia_B *= 1.015  # crescimento de 1.5%
    dias += 1

print(f"Serão necessários {dias} dias para a colônia A ultrapassar ou igualar a colônia B.")
print(f"Tamanho final da colônia A: {colonia_A:.2f}")
print(f"Tamanho final da colônia B: {colonia_B:.2f}")

"""#### Questão 3
Para tratar uma quantidade de 15 dados de avaliações de pessoas usuárias de um serviço da empresa, precisamos verificar se as notas são válidas. Então, escreva um programa que vai receber a nota de 0 a 5 de todos os dados e verificar se é um valor válido. Caso seja inserido uma nota acima de 5 ou abaixo de 0, repita até que a pessoa usuária insira um valor válido.
"""

for i in range(1, 16):
    while True:
        nota = float(input(f"Digite a nota {i} (de 0 a 5): "))
        if 0 <= nota <= 5:
            print(f"Nota {i} registrada com sucesso!")
            break
        else:
            print("Nota inválida! Por favor, insira uma nota entre 0 e 5.")

"""#### Questão 4
Desenvolva um programa que leia um conjunto indeterminado de temperaturas em Celsius e faça uma análise. Portanto, escreva um programa que leia temperaturas e informe a média delas. A leitura deve ser encerrada ao ser enviado o valor -273°C.
"""

soma_temperaturas = 0
contador = 0

while True:
    temperatura = float(input("Digite uma temperatura em Celsius (ou -273 para encerrar): "))
    if temperatura == -273:
        break
    soma_temperaturas += temperatura
    contador += 1
if contador > 0:
    media_temperaturas = soma_temperaturas / contador
    print(f"A média das temperaturas inseridas é: {media_temperaturas:.2f}°C")
else:
    print("Nenhuma temperatura válida foi inserida.")

"""#### Questão 5
Escreva um programa que calcule o fatorial de um número inteiro fornecido pela pessoa usuária. O fatorial de um número inteiro é a multiplicação desse número por todos os seus antecessores até o número 1. Por exemplo, o fatorial de 5 é 5 x 4 x 3 x 2 x 1 = 120.
"""

numero = int(input("Digite um número inteiro para calcular o fatorial: "))

fatorial = 1

if numero < 0:
    print("Não é possível calcular o fatorial de um número negativo.")
else:
    for i in range(1, numero + 1):
        fatorial *= i

    print(f"O fatorial de {numero} é {fatorial}.")

"""### Momento dos projetos

#### Questão 6
Escreva um programa que gere a tabuada de um número inteiro de 1 a 10, de acordo com a escolha da pessoa usuária. Como exemplo, para o número 2, a tabuada deve ser mostrada no seguinte formato:
```
Tabuada do 2:
2 x 1 = 2
2 x 2 = 4
[...]
2 x 10 = 20
```
"""

numero = int(input("Digite um número inteiro de 1 a 10 para ver a tabuada: "))
if 1 <= numero <= 10:
    print(f"Tabuada do {numero}:")
    for i in range(1, 11):
        print(f"{numero} x {i} = {numero * i}")
else:
    print("Por favor, digite um número entre 1 e 10.")

"""#### Questão 7
Os números primos possuem várias aplicações dentro da Ciência de Dados, por exemplo, na criptografia e segurança. Um número primo é aquele que é divisível apenas por um e por ele mesmo. Faça um programa que peça um número inteiro e determine se ele é ou não um número primo.
"""

numero = int(input("Digite um número inteiro para verificar se é primo: "))

if numero < 2:
    print(f"O número {numero} não é primo.")
else:
    primo = True

    for i in range(2, int(numero**0.5) + 1):
        if numero % i == 0:
            primo = False
            break

    if primo:
        print(f"O número {numero} é primo.")
    else:
        print(f"O número {numero} não é primo.")

"""#### Questão 8
Vamos entender a distribuição de idades de pensionistas de uma empresa de previdência. Escreva um programa que leia as idades de uma quantidade não informada de clientes e mostre a distribuição em intervalos de [0-25], [26-50], [51-75] e [76-100]. Encerre a entrada de dados com um número negativo.
"""

faixa_0_25 = 0
faixa_26_50 = 0
faixa_51_75 = 0
faixa_76_100 = 0

while True:
    idade = int(input("Digite a idade do cliente (ou um número negativo para encerrar): "))

    if idade < 0:
        break

    if 0 <= idade <= 25:
        faixa_0_25 += 1
    elif 26 <= idade <= 50:
        faixa_26_50 += 1
    elif 51 <= idade <= 75:
        faixa_51_75 += 1
    elif 76 <= idade <= 100:
        faixa_76_100 += 1
    else:
        print("Idade fora do intervalo considerado (0-100).")

print("\nDistribuição das idades:")
print(f"Faixa [0-25]: {faixa_0_25} clientes")
print(f"Faixa [26-50]: {faixa_26_50} clientes")
print(f"Faixa [51-75]: {faixa_51_75} clientes")
print(f"Faixa [76-100]: {faixa_76_100} clientes")

"""#### Questão 9
Em uma eleição para gerência em uma empresa com 20 funcionários, existem quatro candidatos. Escreva um programa que calcule o vencedor da eleição. A votação ocorreu da seguinte maneira:
- Cada funcionário votou em um dos quatro candidatos (representados pelos números 1, 2, 3 e 4).
- Também foram contabilizados os votos nulos (representado pelo número 5) e os votos em branco (representado pelo número 6).

Ao final da votação, o programa deve exibir o total de votos para cada candidato, o número de votos nulos e o número de votos em branco. Além disso, deve calcular e exibir a porcentagem de votos nulos em relação ao total de votos e a porcentagem de votos em branco em relação ao total de votos.
"""

candidatos = [0, 0, 0, 0]
votos_nulos = 0
votos_brancos = 0
total_votos = 0

for i in range(1, 21):
    voto = int(input(f"Voto do funcionário {i} (1, 2, 3, 4, 5 para nulo, 6 para branco): "))

    if voto in [1, 2, 3, 4]:
        candidatos[voto - 1] += 1
    elif voto == 5:
        votos_nulos += 1
    elif voto == 6:
        votos_brancos += 1
    else:
        print("Voto inválido, por favor insira um número de 1 a 6.")
        continue

    total_votos += 1

print("\nResultados da Eleição:")
for i in range(4):
    print(f"Candidato {i + 1}: {candidatos[i]} votos")
print(f"Votos nulos: {votos_nulos} votos")
print(f"Votos em branco: {votos_brancos} votos")

if total_votos > 0:
    percentual_nulos = (votos_nulos / total_votos) * 100
    percentual_brancos = (votos_brancos / total_votos) * 100
else:
    percentual_nulos = 0
    percentual_brancos = 0

print(f"Porcentagem de votos nulos: {percentual_nulos:.2f}%")
print(f"Porcentagem de votos em branco: {percentual_brancos:.2f}%")

vencedor = candidatos.index(max(candidatos)) + 1
print(f"O vencedor da eleição é o Candidato {vencedor}.")

"""## Aula 5 - Estruturas de dados

### Aquecendo na programação

#### Questão 1
Faça um programa que tenha a seguinte lista contendo os valores de gastos de uma empresa de papel `[2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]`. Com esses valores, faça um programa que calcule a média de gastos. Dica, use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).
"""

gastos = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]
media_gastos = sum(gastos) / len(gastos)
print(f"A média de gastos da empresa é: R$ {media_gastos:.2f}")

"""#### Questão 2
 Com os mesmos dados da questão anterior, defina quantas compras foram acima de 3000 reais e calcule a porcentagem quanto ao total de compras.
"""



"""#### Questão 3
Faça um código que colete em uma lista 5 números inteiros quaisquer e imprima a lista. Exemplo: `[1,4,7,2,4]`.
"""

numeros = []

for i in range(5):
    numero = int(input("Digite um número inteiro: "))
    numeros.append(numero)

print("A lista de números é:", numeros)

"""#### Questão 4
Colete novamente 5 inteiros e imprima a lista em ordem inversa à enviada.
"""

numeros = []

for i in range(5):
    numero = int(input("Digite um número inteiro: "))
    numeros.append(numero)

print("A lista em ordem inversa é:", numeros[::-1])

"""#### Questão 5
Faça um programa que, ao inserir um número qualquer, criará uma lista contendo todos os números primos entre 1 e o número digitado.
"""

def verificar_primo(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

numero = int(input("Digite um número: "))
numeros_primos = [i for i in range(1, numero + 1) if verificar_primo(i)]

print("Os números primos entre 1 e", numero, "são:", numeros_primos)

"""#### Questão 6
Escreva um programa que peça uma data informando o dia, mês e ano e determine se ela é uma data válida para uma análise.
"""

import datetime

def verificar_data(dia, mes, ano):
    try:
        data = datetime.date(ano, mes, dia)
        return True
    except ValueError:
        return False

dia = int(input("Digite o dia: "))
mes = int(input("Digite o mês: "))
ano = int(input("Digite o ano: "))

if verificar_data(dia, mes, ano):
    print(f"A data {dia}/{mes}/{ano} é válida.")
else:
    print(f"A data {dia}/{mes}/{ano} não é válida.")

"""### Momento dos projetos

#### Questão 7
Para um estudo envolvendo o nível de multiplicação de bactérias em uma colônia, foi coletado o número de bactérias multiplicadas por dia, com base em um processo de duplicação diária e pode ser observado a seguir: `[1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]`. Tendo esses valores, faça um código que gere uma lista contendo o percentual de crescimento de bactérias por dia, comparando o número de bactérias em cada dia com o número de bactérias do dia anterior. Dica: para calcular o percentual de crescimento usamos a seguinte equação: `100 * (amostra_atual - amostra_passada) / (amostra_passada)`.
"""

bacterias = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]

percentual_crescimento = []

for i in range(1, len(bacterias)):
    crescimento = 100 * (bacterias[i] - bacterias[i - 1]) / bacterias[i - 1]
    percentual_crescimento.append(crescimento)

print("Percentual de crescimento das bactérias por dia:")
for i, crescimento in enumerate(percentual_crescimento, start=2):
    print(f"Dia {i}: {crescimento:.2f}%")

"""#### Questão 8
Para uma seleção de produtos alimentícios, precisamos separar o conjunto de IDs dados por números inteiros, sabendo que os produtos com ID par são doces e os com ID ímpar são amargos. Monte um código que colete 10 IDs. Depois, calcule e mostre a quantidade de produtos doces e amargos.
"""

doces = 0
amargos = 0

# Coleta dos 10 IDs
for _ in range(10):
    id_produto = int(input("Digite o ID do produto: "))

    if id_produto % 2 == 0:
        doces += 1
    else:
        amargos += 1

print(f"Quantidade de produtos doces (IDs pares): {doces}")
print(f"Quantidade de produtos amargos (IDs ímpares): {amargos}")

"""#### Questão 9
Desenvolva um programa que informa a nota de um aluno de acordo com suas respostas. Ele deve pedir a resposta de um aluno para cada questão e é preciso verificar se a resposta foi igual ao gabarito. Cada questão vale um ponto e existem alternativas:  A, B, C ou D.
```
Gabarito da Prova:
01 - D
02 - A
03 - C
04 - B
05 - A
06 - D
07 - C
08 - C
09 - A
10 - B
```
"""

gabarito = {
    1: 'D', 2: 'A', 3: 'C', 4: 'B', 5: 'A',
    6: 'D', 7: 'C', 8: 'C', 9: 'A', 10: 'B'
}

nota = 0

for i in range(1, 11):  # Para cada questão de 1 a 10
    resposta = input(f"Digite a resposta da questão {i} (A, B, C ou D): ").upper()

    if resposta == gabarito[i]:
        nota += 1

print(f"A nota final do aluno é: {nota}/10")

"""#### Questão 10
Um instituto de meteorologia deseja fazer um estudo de temperatura média de cada mês do ano. Para isso, você precisa fazer um código que colete e armazene essas temperaturas médias em uma lista. Depois, calcule a média anual das temperaturas e mostre todas as temperaturas acima da média anual, e em que mês elas ocorreram, mostrando os meses por extenso: Janeiro, Fevereiro, etc.
"""

meses = [
    'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
    'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
]

temperaturas = []
for mes in meses:
    temperatura = float(input(f"Digite a temperatura média de {mes}: "))
    temperaturas.append(temperatura)

media_anual = sum(temperaturas) / len(temperaturas)

print(f"\nA média anual das temperaturas é: {media_anual:.2f}°C\n")

print("Meses com temperaturas acima da média anual:")
for i in range(len(temperaturas)):
    if temperaturas[i] > media_anual:
        print(f"{meses[i]}: {temperaturas[i]:.2f}°C")

"""#### Questão 11
Uma empresa de e-commerce está interessada em analisar as vendas dos seus produtos. Os dados das vendas foram armazenados em um dicionário:
```
{'Produto A': 300, 'Produto B': 80, 'Produto C': 60,
 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}
```
Escreva um código que calcule o total de vendas e o produto mais vendido.
"""

vendas = {
    'Produto A': 300,
    'Produto B': 80,
    'Produto C': 60,
    'Produto D': 200,
    'Produto E': 250,
    'Produto F': 30
}

total_vendas = sum(vendas.values())

produto_mais_vendido = max(vendas, key=vendas.get)
vendas_produto_mais_vendido = vendas[produto_mais_vendido]

print(f"Total de vendas: {total_vendas}")
print(f"Produto mais vendido: {produto_mais_vendido} com {vendas_produto_mais_vendido} vendas.")

"""#### Questão 12
Uma pesquisa de mercado foi feita para decidir qual design de uma marca infantil mais agrada crianças. A pesquisa foi feita e o votos computados podem ser observados abaixo:
```
'''
Tabela de votos da marca
Design 1 - 1334 votos
Design 2 - 982 votos
Design 3 - 1751 votos
Design 4 - 210 votos
Design 5 - 1811 votos
'''
```
Adapte os dados fornecidos a você para uma estrutura de dicionário e a partir dele, informe o design vencedor e a porcentagem de votos recebidos.

"""

votos = {
    'Design 1': 1334,
    'Design 2': 982,
    'Design 3': 1751,
    'Design 4': 210,
    'Design 5': 1811
}

total_votos = sum(votos.values())

design_vencedor = max(votos, key=votos.get)
votos_design_vencedor = votos[design_vencedor]

porcentagem_votos = (votos_design_vencedor / total_votos) * 100

print(f"Design vencedor: {design_vencedor}")
print(f"Votos do design vencedor: {votos_design_vencedor}")
print(f"Porcentagem de votos: {porcentagem_votos:.2f}%")

"""#### Questão 13
Os funcionários de um setor da empresa que você trabalha vão receber um abono correspondente a 10% do seu salário devido ao ótimo desempenho do time. O setor financeiro solicitou sua ajuda para a verificação das consequências financeiras que esse abono irá gerar nos recursos. Assim, foi encaminhada para você uma lista com os salários que receberão o abono: `[1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]`. O abono de cada funcionário não pode ser inferior a 200. Em código, transforme cada um dos salários em chaves de um dicionário e o abono de cada salário no elemento. Depois, informe o total de gastos com o abono, quantos funcionários receberam o abono mínimo e qual o maior valor de abono fornecido.

"""

salarios = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]

abonos = {}

for salario in salarios:
    abono = salario * 0.10
    # Garantindo que o abono não seja inferior a 200
    if abono < 200:
        abono = 200
    abonos[salario] = abono

total_abonos = sum(abonos.values())
funcionarios_abono_minimo = sum(1 for abono in abonos.values() if abono == 200)
maior_abono = max(abonos.values())

print(f"Total de gastos com o abono: R${total_abonos:.2f}")
print(f"Funcionários que receberam o abono mínimo: {funcionarios_abono_minimo}")
print(f"Maior valor de abono fornecido: R${maior_abono:.2f}")

"""#### Questão 14
Uma equipe de cientistas de dados está estudando a diversidade biológica em uma floresta. A equipe fez a coleta de informações sobre o número de espécies de plantas e animais em cada área da floresta e armazenaram essas informações em um dicionário. Nele, a chave descreve a área dos dados e os valores nas listas correspondem às espécies de plantas e animais nas áreas, respectivamente.
```
{'Área Norte': [2819, 7236],
 'Área Leste': [1440, 9492],
 'Área Sul': [5969, 7496],
 'Área Oeste': [14446, 49688],
 'Área Centro': [22558, 45148]}
```
Escreva um código para calcular a média de espécies por área e identificar a área com a maior diversidade biológica. Dica: use as funções built-in [`sum()`](https://docs.python.org/3/library/functions.html#sum) e [`len()`](https://docs.python.org/3/library/functions.html#len).

"""

dados_areas = {
    'Área Norte': [2819, 7236],
    'Área Leste': [1440, 9492],
    'Área Sul': [5969, 7496],
    'Área Oeste': [14446, 49688],
    'Área Centro': [22558, 45148]
}

maior_diversidade = 0
area_maior_diversidade = ''
total_diversidade = 0
numero_areas = len(dados_areas)

for area, especies in dados_areas.items():
    total_especies = sum(especies)
    media_especies = total_especies / len(especies)
    total_diversidade += total_especies

    if total_especies > maior_diversidade:
        maior_diversidade = total_especies
        area_maior_diversidade = area

media_geral_diversidade = total_diversidade / numero_areas

# Exibindo os resultados
print(f"Média de espécies por área:")
for area, especies in dados_areas.items():
    media_especies = sum(especies) / len(especies)
    print(f"{area}: {media_especies:.2f} espécies")

print(f"\nÁrea com a maior diversidade biológica: {area_maior_diversidade} com {maior_diversidade} espécies no total.")
print(f"Média geral de diversidade: {media_geral_diversidade:.2f} espécies por área.")

"""#### Questão 15
O setor de RH da sua empresa te pediu uma ajuda para analisar as idades dos funcionários de 4 setores da empresa. Para isso, ele te forneceu os seguintes dados:
```
{'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
 'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
 'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
 'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
```
Sabendo que cada setor tem 10 funcionários, construa um código que calcule a média de idade de cada setor, a idade média geral entre todos os setores e quantas pessoas estão acima da idade média geral.

"""

dados_setores = {
    'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
    'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
    'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
    'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]
}

total_idades_geral = 0
total_funcionarios = 0
funcionarios_acima_da_media = 0
media_geral = 0

print("Média de idade por setor:")
for setor, idades in dados_setores.items():
    media_setor = sum(idades) / len(idades)
    total_idades_geral += sum(idades)
    total_funcionarios += len(idades)
    print(f"{setor}: {media_setor:.2f} anos")
media_geral = total_idades_geral / total_funcionarios

# Contando quantos funcionários estão acima da médi
for idades in dados_setores.values():
    for idade in idades:
        if idade > media_geral:
            funcionarios_acima_da_media += 1

# Exibindo a média geral e a quantidade de funcionários acima da média
print(f"\nMédia geral de idade entre todos os setores: {media_geral:.2f} anos")
print(f"Funcionários acima da média geral de idade: {funcionarios_acima_da_media}")